#!/bin/bash

rootPartition=$1
installDisk=$2
efiPartition=$3
swapPartition=$4
Hostname=$5
rootpw1=$6
timezone=$7
locale=$8
CONFIG_FILE="/root/.net_config"

status_complete() {
    printf "%s... Done.\n" "$1"
}

configure_locale() {
    ln -sf /usr/share/zoneinfo/$timezone /etc/localtime
    hwclock --systohc
    echo $locale UTF-8 >> /etc/locale.gen
    locale-gen
    echo LANG=$locale > /etc/locale.conf
    export LANG=$locale
}

configure_hostname() {
    echo "$Hostname" > /etc/hostname
    cat > /etc/hosts << EOF
127.0.0.1 localhost
::1       localhost
127.0.1.1 $Hostname
EOF
}

set_root_password() {
    echo -e "$rootpw1\n$rootpw1" | passwd
    clear
}

# Ethernet setup
check_ethernet() {
    eth_device=$(ip -o link show | awk -F': ' '{print $2}' | grep -E '^e(n|th|np)')
    if [ -n "$eth_device" ]; then
        echo "Found '$eth_device'." >&2
        cat > /etc/systemd/network/20-wired.network << EOF
[Match]
Name=$eth_device

[Link]
RequiredForOnline=routable

[Network]
DHCP=yes

[DHCP]
UseDNS=true
EOF
    else
        echo "No Ethernet interface detected. Skipping Ethernet setup." >&2
    fi
}

check_wifi() {
    # Grabs the first wireless interface name
    wifi_device=$(iw dev | awk '$1=="Interface"{print $2}' | head -n 1)

    if [ -n "$wifi_device" ]; then
        echo "================================================="
        echo "           Wi-Fi Configuration"
        echo "================================================="
        echo "Found Wi-Fi interface: $wifi_device"

        # Check if we have an exported config from the previous script
        if [ -f "$CONFIG_FILE" ]; then
            echo "Found saved network configuration. Automating setup..."
            source "$CONFIG_FILE"
            SSID="$WIFI_SSID"
            WIFIPASS="$WIFI_PASS"
            AUTO_CONF=true
        fi

        if [ "$AUTO_CONF" = true ]; then
            # Create NetworkManager connection profile
            create_nm_config() {
                mkdir -p /etc/NetworkManager/system-connections
                cat > "/etc/NetworkManager/system-connections/$SSID.nmconnection" << EOF
[connection]
id=$SSID
uuid=$(cat /proc/sys/kernel/random/uuid)
type=wifi
match-device=type:wifi

[wifi]
mode=infrastructure
ssid=$SSID

[wifi-security]
auth-alg=open
key-mgmt=wpa-psk
psk=$WIFIPASS

[ipv4]
method=auto

[ipv6]
addr-gen-mode=default
method=auto
EOF
                chmod 600 "/etc/NetworkManager/system-connections/$SSID.nmconnection"
            }
            create_nm_config

            # Optional: Also generate wpa_supplicant.conf if you want a fallback
            if command -v wpa_passphrase &> /dev/null; then
                generate_wpa() {
                    wpa_passphrase "$SSID" "$WIFIPASS" > /etc/wpa_supplicant/wpa_supplicant.conf
                }
                generate_wpa
            fi
        fi
    else
        echo "[INFO] No Wi-Fi interface detected. Skipping Wi-Fi setup."
    fi
}
# Bootloader setup
install_bootloader() {
    bootctl install
}

# UUID setup
configure_boot_entries() {
    uuid=$(lsblk -no UUID "$rootPartition")
    cat > /boot/loader/loader.conf << EOF
default  arch.conf
timeout  4
console-mode max
editor   no
EOF
    cat > /boot/loader/entries/arch.conf << EOF
title   Arch Linux
linux   /vmlinuz-linux-zen
initrd  /initramfs-linux-zen.img
options root=UUID=$uuid rw
EOF
    bootctl update
}

# Enable Multilib
enable_multilib() {
    sed -i -e '/#\[multilib\]/,+1s/^#//' /etc/pacman.conf
}


# Enable services
enable_system_services() {
    system_type=$(hostnamectl | grep "Chassis")

    cat > /etc/systemd/system/first-boot.service << EOF
[Unit]
Description=First Boot User Account Setup
After=multi-user.target
ConditionPathExists=/root/user.conf

[Service]
Type=simple
ExecStart=/root/user.sh
StandardInput=tty-force
StandardOutput=tty
StandardError=tty
TTYPath=/dev/tty1
TTYReset=yes
TTYVHangup=yes
KillMode=process
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
    systemctl enable bluetooth 2>&1 | grep -vE 'Created symlink|is not a native service'
    systemctl enable NetworkManager 2>&1 | grep -vE 'Created symlink|is not a native service'
    systemctl enable systemd-homed 2>&1 | grep -vE 'Created symlink|is not a native service'
    systemctl enable systemd-resolved 2>&1 | grep -vE 'Created symlink|is not a native service'
    systemctl enable cups 2>&1 | grep -vE 'Created symlink|is not a native service'
    systemctl enable docker 2>&1 | grep -vE 'Created symlink|is not a native service'
    systemctl enable first-boot 2>&1 | grep -vE 'Created symlink|is not a native service'
    systemctl mask getty@tty1.service 

    if [[ $system_type == *"laptop"* ]]; then
        if [[ -f /etc/tlp.conf ]]; then
            cp /etc/tlp.conf /etc/tlp.conf.bak
        fi
    fi

        tee /etc/tlp.conf > /dev/null <<EOF
# TLP Configuration - Generated by setup-tlp.sh

# --- CPU Settings ---
CPU_SCALING_GOVERNOR_ON_BAT=powersave
CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_ENERGY_PERF_POLICY_ON_BAT=power
CPU_ENERGY_PERF_POLICY_ON_AC=balance_performance

# --- Battery Charge Thresholds (BAT0) ---
START_CHARGE_THRESH_BAT0=40
STOP_CHARGE_THRESH_BAT0=80

# --- USB Autosuspend ---
USB_AUTOSUSPEND=1

# --- WiFi Power Saving ---
WIFI_PWR_ON_BAT=1

# --- Disk Power Management ---
DISK_APM_LEVEL_ON_BAT="128 128"
DISK_APM_LEVEL_ON_AC="254 254"
EOF
        systemctl enable tlp.service
}

check_ethernet
check_wifi
configure_locale
configure_hostname
set_root_password
install_bootloader
configure_boot_entries
enable_multilib
enable_system_services
exit